---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
- name: kind-local
  groups:
  - k8s
  image: bsycorp/kind:latest-1.16
  privileged: True
  override_command: no
  exposed_ports:
    - 8443/tcp
    - 10080/tcp
  published_ports:
    - 0.0.0.0:${TEST_CLUSTER_PORT:-24443}:8443/tcp
  pre_build_image: yes
  volumes:
    - ${MOLECULE_PROJECT_DIRECTORY}:/build:Z
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
    enabled: False
  inventory:
    group_vars:
      all:
        namespace: ${TEST_NAMESPACE:-reproducer}
  env:
    K8S_AUTH_KUBECONFIG: /tmp/molecule/kind-local/kubeconfig
    KUBECONFIG: /tmp/molecule/kind-local/kubeconfig
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
    KIND_PORT: '${TEST_CLUSTER_PORT:-24443}'
verifier:
  name: ansible
  lint:
    name: ansible-lint
