---

- name: Build Operator in Kubernetes docker container
  hosts: k8s
  vars:
    image_name: debug.fabianism.us/reproducer-operator:testing
  tasks:
  # using command so we don't need to install any dependencies
  - name: Get existing image hash
    command: docker images -q {{ image_name }}
    register: prev_hash
    changed_when: false

  - name: Build Operator Image
    command: docker build -f /build/build/Dockerfile -t {{ image_name }} /build
    register: build_cmd
    changed_when: not prev_hash.stdout or (prev_hash.stdout and prev_hash.stdout not in ''.join(build_cmd.stdout_lines[-2:]))

- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    pull_policy: Never
    REPLACE_IMAGE: debug.fabianism.us/reproducer-operator:testing
    custom_resource: "{{ lookup('file', '/'.join([deploy_dir, 'crds/debug_v1alpha1_reproducer_cr.yaml'])) | from_yaml }}"
  tasks:
    - name: Create the Operator Deployment
      k8s:
        namespace: '{{ namespace }}'
        definition: "{{ lookup('template', '/'.join([deploy_dir, 'operator.yaml'])) }}"
        wait: yes

    - name: Create the debug.fabianism.us/v1alpha1.Reproducer
      k8s:
        state: present
        namespace: '{{ namespace }}'
        definition: '{{ custom_resource }}'
