sudo: required
services: docker
language: python
install:
  - pip install docker molecule openshift jmespath
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.11.3/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
script:
  - molecule test -s local
