apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: reproducers.debug.fabianism.us
spec:
  group: debug.fabianism.us
  names:
    kind: Reproducer
    listKind: ReproducerList
    plural: reproducers
    singular: reproducer
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
